# Load environment variables from ../.env file
name: hilos-main

services:
  hilos:
    build: .
    env_file:
      - ../.env
    container_name: hilos-daemon
    volumes:
      - ..:/app
      - ../data/logs:/var/log/hilos
      - ../data/run:/var/run
    working_dir: /app
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d
      - HTTP_STATUS_HOST=${HTTP_STATUS_HOST:-0.0.0.0}
      - HTTP_STATUS_PORT=${HTTP_STATUS_PORT:-8090}
      - WORKER_COMM_HOST=${WORKER_COMM_HOST:-0.0.0.0}
      - WORKER_COMM_PORT=${WORKER_COMM_PORT:-8091}
      - DB_HOST=${DB_HOST:-hilos-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-hilos_db}
      - DB_USER=${DB_USER:-hilos_user}
      - DB_PASSWORD=${DB_PASSWORD:-hilos_user_password}
    command: ["php", "framework/src/Bootstrap/docker.php"]
    expose:
      - "${HTTP_STATUS_PORT:-8090}"
      - "${WORKER_COMM_PORT:-8091}"
    depends_on:
      - hilos-mysql
    networks:
      hilos-network:
        ipv4_address: ${DOCKER_DAEMON_IP:-172.25.0.10}

  hilos-mysql:
    image: mariadb:11.4
    env_file:
      - ../.env
    container_name: hilos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-hilos_password_2024}
      MARIADB_AUTO_UPGRADE: "1"
      MYSQL_DATABASE: ${DB_NAME:-hilos_db}
      MYSQL_USER: ${DB_USER:-hilos_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-hilos_user_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - hilos_mysql_data:/var/lib/mysql
      - ../data/mysql/backup:/root/backup
      - ../data/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - hilos-network

  hilos-cli:
    build: .
    env_file:
      - ../.env
    container_name: hilos-cli
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - TERM=xterm-256color
      - HILOS_DAEMON_HOST=${HILOS_DAEMON_HOST:-172.25.0.10}
      - HTTP_STATUS_PORT=${HTTP_STATUS_PORT:-8090}
      - WORKER_COMM_PORT=${WORKER_COMM_PORT:-8091}
    profiles:
      - composer
    networks:
      - hilos-network

  hilos-monitor:
    build: .
    env_file:
      - ../.env
    container_name: hilos-monitor
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - HILOS_DAEMON_HOST=${HILOS_DAEMON_HOST:-172.25.0.10}
      - HTTP_STATUS_PORT=${HTTP_STATUS_PORT:-8090}
      - WORKER_COMM_PORT=${WORKER_COMM_PORT:-8091}
    profiles:
      - monitor
    networks:
      - hilos-network

volumes:
  hilos_mysql_data:

networks:
  hilos-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET:-172.25.0.0/16}
