import type { RouteRecordRaw } from 'vue-router'

export type HilosRouteOverrides = Partial<Record<string, NonNullable<RouteRecordRaw['component']>>>

const withOverride = (
  overrides: HilosRouteOverrides | undefined,
  routeName: string,
  fallback: NonNullable<RouteRecordRaw['component']>,
): NonNullable<RouteRecordRaw['component']> => overrides?.[routeName] ?? fallback

/**
 * Factory returning all /hilos/* routes with lazy-loaded components.
 * Demo projects spread these into their route children array.
 */
export function createHilosRoutes(overrides?: HilosRouteOverrides): RouteRecordRaw[] {
  return [
    {
      path: 'hilos',
      name: 'hilos',
      component: withOverride(overrides, 'hilos', () => import('../views/Hilos/HilosDashboard.vue')),
      meta: { page: 'hilos' },
    },
    {
      path: 'hilos/users/:userId',
      name: 'hilos_user',
      component: withOverride(overrides, 'hilos_user', () => import('../views/Hilos/HilosUserDetail.vue')),
      meta: { page: 'hilos_user' },
    },
    {
      path: 'hilos/users',
      name: 'hilos_users',
      component: withOverride(overrides, 'hilos_users', () => import('../views/Hilos/HilosUsers.vue')),
      meta: { page: 'hilos_users' },
    },
    {
      path: 'hilos/operations',
      name: 'hilos_operations',
      component: withOverride(overrides, 'hilos_operations', () => import('../views/Hilos/HilosOperations.vue')),
      meta: { page: 'hilos_operations' },
    },
    {
      path: 'hilos/roles',
      name: 'hilos_roles',
      component: withOverride(overrides, 'hilos_roles', () => import('../views/Hilos/HilosRoles.vue')),
      meta: { page: 'hilos_roles' },
    },
    {
      path: 'hilos/backup',
      name: 'hilos_backup',
      component: withOverride(overrides, 'hilos_backup', () => import('../views/Hilos/Backup/HilosBackup.vue')),
      meta: { page: 'hilos_backup' },
    },
    {
      path: 'hilos/change-log/tables/:tableId',
      name: 'hilos_change_log_table',
      component: withOverride(overrides, 'hilos_change_log_table', () => import('../views/Hilos/ChangeLog/HilosChangeLogTable.vue')),
      meta: { page: 'hilos_change_log_table' },
    },
    {
      path: 'hilos/change-log/tables',
      name: 'hilos_change_log_tables',
      component: withOverride(overrides, 'hilos_change_log_tables', () => import('../views/Hilos/ChangeLog/HilosChangeLogTables.vue')),
      meta: { page: 'hilos_change_log_tables' },
    },
    {
      path: 'hilos/change-log',
      name: 'hilos_change_log',
      component: withOverride(overrides, 'hilos_change_log', () => import('../views/Hilos/ChangeLog/HilosChangeLogDashboard.vue')),
      meta: { page: 'hilos_change_log' },
    },
    {
      path: 'hilos/daemon/http/:serverId',
      name: 'hilos_daemon_http_server',
      component: withOverride(overrides, 'hilos_daemon_http_server', () => import('../views/Hilos/Daemon/HilosDaemonHttpServer.vue')),
      meta: { page: 'hilos_daemon_http_server' },
    },
    {
      path: 'hilos/daemon/workers',
      name: 'hilos_daemon_workers',
      component: withOverride(overrides, 'hilos_daemon_workers', () => import('../views/Hilos/Daemon/HilosDaemonWorkers.vue')),
      meta: { page: 'hilos_daemon_workers' },
    },
    {
      path: 'hilos/daemon/agents',
      name: 'hilos_daemon_agents',
      component: withOverride(overrides, 'hilos_daemon_agents', () => import('../views/Hilos/Daemon/HilosDaemonAgents.vue')),
      meta: { page: 'hilos_daemon_agents' },
    },
    {
      path: 'hilos/daemon/cron',
      name: 'hilos_daemon_cron',
      component: withOverride(overrides, 'hilos_daemon_cron', () => import('../views/Hilos/Daemon/HilosDaemonCron.vue')),
      meta: { page: 'hilos_daemon_cron' },
    },
    {
      path: 'hilos/daemon/websockets',
      name: 'hilos_daemon_websockets',
      component: withOverride(overrides, 'hilos_daemon_websockets', () => import('../views/Hilos/Daemon/HilosDaemonWebsockets.vue')),
      meta: { page: 'hilos_daemon_websockets' },
    },
    {
      path: 'hilos/daemon',
      name: 'hilos_daemon',
      component: withOverride(overrides, 'hilos_daemon', () => import('../views/Hilos/Daemon/HilosDaemon.vue')),
      meta: { page: 'hilos_daemon' },
    },
    {
      path: 'hilos/logs/view',
      name: 'hilos_logs_view',
      component: withOverride(overrides, 'hilos_logs_view', () => import('../views/Hilos/LogViewer/HilosLogsView.vue')),
      meta: { page: 'hilos_logs_view' },
    },
    {
      path: 'hilos/logs/keys',
      name: 'hilos_logs_keys',
      component: withOverride(overrides, 'hilos_logs_keys', () => import('../views/Hilos/LogViewer/HilosLogsKeys.vue')),
      meta: { page: 'hilos_logs_keys' },
    },
    {
      path: 'hilos/logs/workers',
      name: 'hilos_logs_workers',
      component: withOverride(overrides, 'hilos_logs_workers', () => import('../views/Hilos/LogViewer/HilosLogsWorkers.vue')),
      meta: { page: 'hilos_logs_workers' },
    },
    {
      path: 'hilos/logs/rotations',
      name: 'hilos_logs_rotations',
      component: withOverride(overrides, 'hilos_logs_rotations', () => import('../views/Hilos/LogViewer/HilosLogsRotations.vue')),
      meta: { page: 'hilos_logs_rotations' },
    },
    {
      path: 'hilos/logs',
      name: 'hilos_logs',
      component: withOverride(overrides, 'hilos_logs', () => import('../views/Hilos/LogViewer/HilosLogs.vue')),
      meta: { page: 'hilos_logs' },
    },
    {
      path: 'hilos/settings',
      name: 'hilos_settings',
      component: withOverride(overrides, 'hilos_settings', () => import('../views/Hilos/HilosSettings.vue')),
      meta: { page: 'hilos_settings' },
    },
    {
      path: 'hilos/i18n',
      name: 'hilos_i18n',
      component: withOverride(overrides, 'hilos_i18n', () => import('../views/Hilos/HilosI18n.vue')),
      meta: { page: 'hilos_i18n' },
    },
    {
      path: 'hilos/i18n/translate/ui-page/:uiPageId/item/:itemId',
      name: 'hilos_i18n_translate_ui_page_item',
      component: withOverride(overrides, 'hilos_i18n_translate_ui_page_item', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateUiPageItem.vue')),
      meta: { page: 'hilos_i18n_translate_ui_page_item' },
    },
    {
      path: 'hilos/i18n/translate/group/:groupId/item/:itemId',
      name: 'hilos_i18n_translate_group_item',
      component: withOverride(overrides, 'hilos_i18n_translate_group_item', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateGroupItem.vue')),
      meta: { page: 'hilos_i18n_translate_group_item' },
    },
    {
      path: 'hilos/i18n/translate/action/:actionId/error/:errorId',
      name: 'hilos_i18n_translate_action_error',
      component: withOverride(overrides, 'hilos_i18n_translate_action_error', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateActionError.vue')),
      meta: { page: 'hilos_i18n_translate_action_error' },
    },
    {
      path: 'hilos/i18n/translate/entity/:entityId',
      name: 'hilos_i18n_translate_entity',
      component: withOverride(overrides, 'hilos_i18n_translate_entity', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateEntity.vue')),
      meta: { page: 'hilos_i18n_translate_entity' },
    },
    {
      path: 'hilos/i18n/translate/ui-page/:uiPageId',
      name: 'hilos_i18n_translate_ui_page',
      component: withOverride(overrides, 'hilos_i18n_translate_ui_page', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateUiPage.vue')),
      meta: { page: 'hilos_i18n_translate_ui_page' },
    },
    {
      path: 'hilos/i18n/translate/group/:groupId',
      name: 'hilos_i18n_translate_group',
      component: withOverride(overrides, 'hilos_i18n_translate_group', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateGroup.vue')),
      meta: { page: 'hilos_i18n_translate_group' },
    },
    {
      path: 'hilos/i18n/translate/email/:emailId',
      name: 'hilos_i18n_translate_email',
      component: withOverride(overrides, 'hilos_i18n_translate_email', () => import('../views/Hilos/I18n/Translate/HilosI18nTranslateEmail.vue')),
      meta: { page: 'hilos_i18n_translate_email' },
    },
    {
      path: 'hilos/i18n/languages/:languageId',
      name: 'hilos_i18n_language',
      component: withOverride(overrides, 'hilos_i18n_language', () => import('../views/Hilos/I18n/Details/HilosI18nLanguageDetail.vue')),
      meta: { page: 'hilos_i18n_language' },
    },
    {
      path: 'hilos/i18n/languages',
      name: 'hilos_i18n_languages',
      component: withOverride(overrides, 'hilos_i18n_languages', () => import('../views/Hilos/I18n/Lists/HilosI18nLanguagesList.vue')),
      meta: { page: 'hilos_i18n_languages' },
    },
    {
      path: 'hilos/i18n/countries/:countryId',
      name: 'hilos_i18n_country',
      component: withOverride(overrides, 'hilos_i18n_country', () => import('../views/Hilos/I18n/Details/HilosI18nCountryDetail.vue')),
      meta: { page: 'hilos_i18n_country' },
    },
    {
      path: 'hilos/i18n/countries',
      name: 'hilos_i18n_countries',
      component: withOverride(overrides, 'hilos_i18n_countries', () => import('../views/Hilos/I18n/Lists/HilosI18nCountriesList.vue')),
      meta: { page: 'hilos_i18n_countries' },
    },
    {
      path: 'hilos/i18n/entities',
      name: 'hilos_i18n_entities',
      component: withOverride(overrides, 'hilos_i18n_entities', () => import('../views/Hilos/I18n/Lists/HilosI18nEntitiesList.vue')),
      meta: { page: 'hilos_i18n_entities' },
    },
    {
      path: 'hilos/i18n/ui-pages/:uiPageId',
      name: 'hilos_i18n_ui_page',
      component: withOverride(overrides, 'hilos_i18n_ui_page', () => import('../views/Hilos/I18n/Details/HilosI18nUiPageDetail.vue')),
      meta: { page: 'hilos_i18n_ui_page' },
    },
    {
      path: 'hilos/i18n/ui-pages',
      name: 'hilos_i18n_ui_pages',
      component: withOverride(overrides, 'hilos_i18n_ui_pages', () => import('../views/Hilos/I18n/Lists/HilosI18nUiPagesList.vue')),
      meta: { page: 'hilos_i18n_ui_pages' },
    },
    {
      path: 'hilos/i18n/groups/:groupId',
      name: 'hilos_i18n_group',
      component: withOverride(overrides, 'hilos_i18n_group', () => import('../views/Hilos/I18n/Details/HilosI18nGroupDetail.vue')),
      meta: { page: 'hilos_i18n_group' },
    },
    {
      path: 'hilos/i18n/groups',
      name: 'hilos_i18n_groups',
      component: withOverride(overrides, 'hilos_i18n_groups', () => import('../views/Hilos/I18n/Lists/HilosI18nGroupsList.vue')),
      meta: { page: 'hilos_i18n_groups' },
    },
    {
      path: 'hilos/i18n/actions/:actionId',
      name: 'hilos_i18n_action',
      component: withOverride(overrides, 'hilos_i18n_action', () => import('../views/Hilos/I18n/Details/HilosI18nActionDetail.vue')),
      meta: { page: 'hilos_i18n_action' },
    },
    {
      path: 'hilos/i18n/actions',
      name: 'hilos_i18n_actions',
      component: withOverride(overrides, 'hilos_i18n_actions', () => import('../views/Hilos/I18n/Lists/HilosI18nActionsList.vue')),
      meta: { page: 'hilos_i18n_actions' },
    },
    {
      path: 'hilos/i18n/emails',
      name: 'hilos_i18n_emails',
      component: withOverride(overrides, 'hilos_i18n_emails', () => import('../views/Hilos/I18n/Lists/HilosI18nEmailsList.vue')),
      meta: { page: 'hilos_i18n_emails' },
    },
    {
      path: 'hilos/guardian',
      name: 'hilos_guardian',
      component: withOverride(overrides, 'hilos_guardian', () => import('../views/Hilos/HilosGuardian.vue')),
      meta: { page: 'hilos_guardian' },
    },
    {
      path: 'hilos/guardian/:agentId',
      name: 'hilos_guardian_agent',
      component: withOverride(overrides, 'hilos_guardian_agent', () => import('../views/Hilos/HilosGuardianAgent.vue')),
      meta: { page: 'hilos_guardian_agent' },
    },
    {
      path: 'hilos/analytics',
      name: 'hilos_analytics',
      component: withOverride(overrides, 'hilos_analytics', () => import('../views/Hilos/HilosAnalytics.vue')),
      meta: { page: 'hilos_analytics' },
    },
    {
      path: 'hilos/mcp-skills/:mcpId/logs/view',
      name: 'hilos_mcp_skills_mcp_logs_view',
      component: withOverride(overrides, 'hilos_mcp_skills_mcp_logs_view', () => import('../views/Hilos/McpSkills/HilosMcpSkillsMcpLogsView.vue')),
      meta: { page: 'hilos_mcp_skills_mcp_logs_view' },
    },
    {
      path: 'hilos/mcp-skills/:mcpId/logs',
      name: 'hilos_mcp_skills_mcp_logs',
      component: withOverride(overrides, 'hilos_mcp_skills_mcp_logs', () => import('../views/Hilos/McpSkills/HilosMcpSkillsMcpLogs.vue')),
      meta: { page: 'hilos_mcp_skills_mcp_logs' },
    },
    {
      path: 'hilos/mcp-skills/:mcpId',
      name: 'hilos_mcp_skills_mcp',
      component: withOverride(overrides, 'hilos_mcp_skills_mcp', () => import('../views/Hilos/McpSkills/HilosMcpSkillsMcp.vue')),
      meta: { page: 'hilos_mcp_skills_mcp' },
    },
    {
      path: 'hilos/mcp-skills',
      name: 'hilos_mcp_skills',
      component: withOverride(overrides, 'hilos_mcp_skills', () => import('../views/Hilos/McpSkills/HilosMcpSkillsDashboard.vue')),
      meta: { page: 'hilos_mcp_skills' },
    },
    {
      path: 'hilos/sil/requests',
      name: 'hilos_sil_requests',
      component: withOverride(overrides, 'hilos_sil_requests', () => import('../views/Hilos/Sil/HilosSilRequests.vue')),
      meta: { page: 'hilos_sil_requests' },
    },
    {
      path: 'hilos/sil/users/:userId',
      name: 'hilos_sil_user_history',
      component: withOverride(overrides, 'hilos_sil_user_history', () => import('../views/Hilos/Sil/HilosSilUserHistory.vue')),
      meta: { page: 'hilos_sil_user_history' },
    },
    {
      path: 'hilos/sil',
      name: 'hilos_sil',
      component: withOverride(overrides, 'hilos_sil', () => import('../views/Hilos/Sil/HilosSilDashboard.vue')),
      meta: { page: 'hilos_sil' },
    },
    {
      path: 'hilos/billing/:providerId/refunds',
      name: 'hilos_billing_refunds',
      component: withOverride(overrides, 'hilos_billing_refunds', () => import('../views/Hilos/Billing/HilosBillingRefunds.vue')),
      meta: { page: 'hilos_billing_refunds' },
    },
    {
      path: 'hilos/billing/:providerId/payments',
      name: 'hilos_billing_payments',
      component: withOverride(overrides, 'hilos_billing_payments', () => import('../views/Hilos/Billing/HilosBillingPayments.vue')),
      meta: { page: 'hilos_billing_payments' },
    },
    {
      path: 'hilos/billing/:providerId',
      name: 'hilos_billing_provider',
      component: withOverride(overrides, 'hilos_billing_provider', () => import('../views/Hilos/Billing/HilosBillingProvider.vue')),
      meta: { page: 'hilos_billing_provider' },
    },
    {
      path: 'hilos/billing',
      name: 'hilos_billing',
      component: withOverride(overrides, 'hilos_billing', () => import('../views/Hilos/Billing/HilosBilling.vue')),
      meta: { page: 'hilos_billing' },
    },
    {
      path: 'hilos/security/oauth/:providerId',
      name: 'hilos_security_oauth_provider',
      component: withOverride(overrides, 'hilos_security_oauth_provider', () => import('../views/Hilos/Security/HilosSecurityOAuthProvider.vue')),
      meta: { page: 'hilos_security_oauth_provider' },
    },
    {
      path: 'hilos/security/oauth',
      name: 'hilos_security_oauth',
      component: withOverride(overrides, 'hilos_security_oauth', () => import('../views/Hilos/Security/HilosSecurityOAuth.vue')),
      meta: { page: 'hilos_security_oauth' },
    },
    {
      path: 'hilos/security/2fa',
      name: 'hilos_security_2fa',
      component: withOverride(overrides, 'hilos_security_2fa', () => import('../views/Hilos/Security/HilosSecurityTwoFactor.vue')),
      meta: { page: 'hilos_security_2fa' },
    },
    {
      path: 'hilos/security',
      name: 'hilos_security',
      component: withOverride(overrides, 'hilos_security', () => import('../views/Hilos/HilosSecurity.vue')),
      meta: { page: 'hilos_security' },
    },
    {
      path: 'hilos/communications/:channelId/deliveries',
      name: 'hilos_communications_deliveries',
      component: withOverride(overrides, 'hilos_communications_deliveries', () => import('../views/Hilos/Communications/HilosCommunicationsDeliveries.vue')),
      meta: { page: 'hilos_communications_deliveries' },
    },
    {
      path: 'hilos/communications/:channelId',
      name: 'hilos_communications_channel',
      component: withOverride(overrides, 'hilos_communications_channel', () => import('../views/Hilos/Communications/HilosCommunicationsChannel.vue')),
      meta: { page: 'hilos_communications_channel' },
    },
    {
      path: 'hilos/communications',
      name: 'hilos_communications',
      component: withOverride(overrides, 'hilos_communications', () => import('../views/Hilos/HilosCommunications.vue')),
      meta: { page: 'hilos_communications' },
    },
  ]
}
