<?php

declare(strict_types=1);

/**
 * Cross-tool AI tooling installer for Hilos.
 *
 * Materializes per-tool AI configuration from the single source of truth
 * (`agents.md` + `docs/agents/` + `skills/hilos-*`) into the locations each
 * assistant discovers. The same idempotent pass performs first-run install,
 * repair (heals missing or wrong artifacts), and update (propagates canonical
 * changes); orphaned managed artifacts are pruned.
 *
 * Per artifact the strategy is chosen by how the tool discovers it:
 *   - symlink where the tool reads by an explicit named path,
 *   - copy/generate where the tool walks a directory (those walks skip symlinks).
 *
 * Generated artifacts are git-ignored and machine-local; every contributor runs
 * the installer to get artifacts correct for their OS. Run via:
 *
 *   composer ai:install            install / repair / update
 *   composer ai:install:check      report drift without changing anything (CI)
 *   php scripts/install-ai-tooling.php --copy-only    no symlinks (Windows/CI)
 *
 * Canonical sources, the tracked adapters (`CLAUDE.md`, `.cursor/rules/*`), and
 * the artifact map are documented in docs/agents/ai-tools.md.
 */

/** How a single artifact is materialized into the working tree. */
enum InstallStrategy
{
    /** Copy each `skills/hilos-*` directory into a tool's real skills directory. */
    case CopySkillTrees;
    /** Symlink each `skills/hilos-*` directory into a real parent (copy fallback). */
    case LinkSkillTrees;
    /** Single file symlink to a canonical file (copy fallback). */
    case SymlinkFile;
    /** Write fully-owned generated content. */
    case GenerateFile;
}

/** Outcome of materializing one path; drives the summary and exit code. */
enum ArtifactStatus: string
{
    case Created = 'created';
    case Updated = 'updated';
    case Repaired = 'repaired';
    case Ok = 'ok';
    case Pruned = 'pruned';
    case Skipped = 'skipped';
    case Blocked = 'blocked';

    public function isChange(): bool
    {
        return match ($this) {
            self::Created, self::Updated, self::Repaired, self::Pruned => true,
            self::Ok, self::Skipped, self::Blocked => false,
        };
    }
}

/**
 * Declarative description of one artifact the installer manages.
 *
 * This script stays compatible with the host PHP (8.1+) on purpose: it is a
 * dev-machine setup tool that must run without the framework's 8.4 docker
 * toolchain, so it avoids 8.2+-only syntax while remaining valid on 8.4.
 */
final class ArtifactSpec
{
    public function __construct(
        public readonly string $label,
        public readonly string $tools,
        public readonly InstallStrategy $strategy,
        public readonly string $target,
        public readonly ?string $source = null,
        public readonly ?string $sourceGlob = null,
        public readonly ?string $generatedBody = null,
        public readonly bool $caseSensitiveOnly = false,
    ) {
    }
}

final class AiToolingInstaller
{
    private const GENERATED_MARKER = 'generated by hilos composer ai:install';
    private const MANAGED_CHILD_PREFIX = 'hilos-';

    private int $changes = 0;
    private int $blocks = 0;

    public function __construct(
        private readonly string $repoRoot,
        private readonly bool $copyOnly,
        private readonly bool $dryRun,
    ) {
    }

    /** @return list<ArtifactSpec> */
    public static function artifacts(): array
    {
        $geminiBody = "<!-- " . self::GENERATED_MARKER . " — do not edit; canonical source: agents.md + docs/agents/ -->\n"
            . "# Hilos Framework\n\n"
            . "@./agents.md\n";

        $aiderBody = "# " . self::GENERATED_MARKER . " — do not edit; canonical source: agents.md + docs/agents/\n"
            . "read:\n"
            . "  - agents.md\n";

        return [
            new ArtifactSpec(
                label: 'Claude Code skills',
                tools: 'Claude Code',
                strategy: InstallStrategy::CopySkillTrees,
                target: '.claude/skills',
                sourceGlob: 'skills/' . self::MANAGED_CHILD_PREFIX . '*',
            ),
            new ArtifactSpec(
                label: 'Shared skill tree',
                tools: 'Codex, Cursor, Windsurf',
                strategy: InstallStrategy::LinkSkillTrees,
                target: '.agents/skills',
                sourceGlob: 'skills/' . self::MANAGED_CHILD_PREFIX . '*',
            ),
            new ArtifactSpec(
                label: 'AGENTS.md entry point',
                tools: 'Codex, Cursor, Windsurf, Aider',
                strategy: InstallStrategy::SymlinkFile,
                target: 'AGENTS.md',
                source: 'agents.md',
                caseSensitiveOnly: true,
            ),
            new ArtifactSpec(
                label: 'Gemini context',
                tools: 'Gemini CLI',
                strategy: InstallStrategy::GenerateFile,
                target: 'GEMINI.md',
                generatedBody: $geminiBody,
            ),
            new ArtifactSpec(
                label: 'Aider config',
                tools: 'Aider',
                strategy: InstallStrategy::GenerateFile,
                target: '.aider.conf.yml',
                generatedBody: $aiderBody,
            ),
        ];
    }

    /** Run the full pass and return a process exit code. */
    public function run(): int
    {
        $caseInsensitive = $this->filesystemIsCaseInsensitive();
        $symlinkCapable = $this->copyOnly ? false : $this->filesystemSupportsSymlinks();

        echo "Hilos AI tooling installer\n";
        echo "  repo:     {$this->repoRoot}\n";
        echo '  mode:     ' . ($this->dryRun ? 'check (no changes)' : 'install / repair / update') . "\n";
        echo '  symlinks: ' . ($symlinkCapable ? 'enabled' : 'disabled (copy / generate only)') . "\n";
        echo '  fs:       ' . ($caseInsensitive ? 'case-insensitive' : 'case-sensitive') . "\n\n";

        foreach (self::artifacts() as $spec) {
            echo "{$spec->label}  ({$spec->tools})\n";

            if ($spec->caseSensitiveOnly && $caseInsensitive) {
                $this->report(ArtifactStatus::Skipped, $spec->target, 'case-insensitive filesystem already resolves it');
                echo "\n";
                continue;
            }

            match ($spec->strategy) {
                InstallStrategy::CopySkillTrees => $this->installSkillTrees($spec, false),
                InstallStrategy::LinkSkillTrees => $this->installSkillTrees($spec, $symlinkCapable),
                InstallStrategy::SymlinkFile => $this->installEntryPointFile($spec, $symlinkCapable),
                InstallStrategy::GenerateFile => $this->installGeneratedFile($spec),
            };
            echo "\n";
        }

        return $this->summary();
    }

    /** Copy or per-child symlink every `skills/hilos-*` directory into the target root. */
    private function installSkillTrees(ArtifactSpec $spec, bool $linkChildren): void
    {
        $sources = $this->globSkillDirectories($spec->sourceGlob ?? '');
        if ($sources === []) {
            $this->report(ArtifactStatus::Skipped, $spec->target, 'no source skill directories found');
            return;
        }

        $targetRoot = $this->absolute($spec->target);
        $this->ensureDirectory($targetRoot);

        $expected = [];
        foreach ($sources as $sourceDir) {
            $name = basename($sourceDir);
            $expected[$name] = true;
            $childTarget = $targetRoot . '/' . $name;

            if ($linkChildren) {
                $this->ensureSymlink($this->relativePath(dirname($childTarget), $sourceDir), $childTarget, $spec->target . '/' . $name);
            } else {
                $this->syncDirectory($sourceDir, $childTarget, $spec->target . '/' . $name);
            }
        }

        $this->pruneManagedChildren($targetRoot, $expected, $spec->target);
    }

    /** Maintain a single entry-point file as a symlink (or a real copy in copy mode). */
    private function installEntryPointFile(ArtifactSpec $spec, bool $symlinkCapable): void
    {
        $source = $this->absolute((string) $spec->source);
        if (!is_file($source)) {
            $this->report(ArtifactStatus::Skipped, $spec->target, "canonical source missing: {$spec->source}");
            return;
        }

        $target = $this->absolute($spec->target);

        if ($symlinkCapable) {
            $this->ensureSymlink($this->relativePath(dirname($target), $source), $target, $spec->target);
            return;
        }

        // Copy fallback: only own the file when it is absent or already equals the source.
        if (is_link($target) || (file_exists($target) && !$this->fileEquals($target, $source))) {
            $this->report(ArtifactStatus::Blocked, $spec->target, 'unexpected existing file; not overwriting');
            return;
        }
        if (is_file($target) && $this->fileEquals($target, $source)) {
            $this->report(ArtifactStatus::Ok, $spec->target);
            return;
        }
        if (!$this->dryRun) {
            copy($source, $target);
        }
        $this->report(ArtifactStatus::Created, $spec->target, 'copied (no symlink support)');
    }

    /** Write a fully-owned generated file, refusing to clobber a foreign file at the path. */
    private function installGeneratedFile(ArtifactSpec $spec): void
    {
        $target = $this->absolute($spec->target);
        $body = (string) $spec->generatedBody;

        if (file_exists($target) && !is_link($target) && !str_contains((string) file_get_contents($target), self::GENERATED_MARKER)) {
            $this->report(ArtifactStatus::Blocked, $spec->target, 'existing non-generated file; not overwriting');
            return;
        }
        if (is_file($target) && !is_link($target) && file_get_contents($target) === $body) {
            $this->report(ArtifactStatus::Ok, $spec->target);
            return;
        }

        $existed = file_exists($target) || is_link($target);
        if (!$this->dryRun) {
            if (is_link($target)) {
                unlink($target);
            }
            file_put_contents($target, $body);
        }
        $this->report($existed ? ArtifactStatus::Updated : ArtifactStatus::Created, $spec->target);
    }

    /** Ensure $linkPath is a symlink pointing at $relativeTarget; repair if wrong, refuse foreign files. */
    private function ensureSymlink(string $relativeTarget, string $linkPath, string $displayPath): void
    {
        if (is_link($linkPath)) {
            if (readlink($linkPath) === $relativeTarget) {
                $this->report(ArtifactStatus::Ok, $displayPath);
                return;
            }
            if (!$this->dryRun) {
                unlink($linkPath);
                symlink($relativeTarget, $linkPath);
            }
            $this->report(ArtifactStatus::Repaired, $displayPath, "→ {$relativeTarget}");
            return;
        }

        if (file_exists($linkPath)) {
            $this->report(ArtifactStatus::Blocked, $displayPath, 'existing non-symlink file/dir; not replacing');
            return;
        }

        if (!$this->dryRun) {
            symlink($relativeTarget, $linkPath);
        }
        $this->report(ArtifactStatus::Created, $displayPath, "→ {$relativeTarget}");
    }

    /** Mirror $source directory into $target, copying changed files and removing extras. */
    private function syncDirectory(string $source, string $target, string $displayPath): void
    {
        $existedAsTree = is_dir($target) && !is_link($target);
        if (is_link($target)) {
            $this->report(ArtifactStatus::Blocked, $displayPath, 'existing symlink where a copy is required; not replacing');
            return;
        }
        $this->ensureDirectory($target);

        $changed = false;
        $keep = [];
        foreach ($this->directoryEntries($source) as $entry) {
            $keep[$entry] = true;
            $sourcePath = $source . '/' . $entry;
            $targetPath = $target . '/' . $entry;
            if (is_dir($sourcePath)) {
                $this->syncDirectorySilently($sourcePath, $targetPath, $changed);
                continue;
            }
            if (!is_file($targetPath) || !$this->fileEquals($targetPath, $sourcePath)) {
                if (!$this->dryRun) {
                    copy($sourcePath, $targetPath);
                }
                $changed = true;
            }
        }
        $changed = $this->removeExtraEntries($target, $keep) || $changed;

        if (!$existedAsTree) {
            $this->report(ArtifactStatus::Created, $displayPath);
        } elseif ($changed) {
            $this->report(ArtifactStatus::Updated, $displayPath);
        } else {
            $this->report(ArtifactStatus::Ok, $displayPath);
        }
    }

    /** Recursive copy step used inside syncDirectory; aggregates the changed flag by reference. */
    private function syncDirectorySilently(string $source, string $target, bool &$changed): void
    {
        if (!is_dir($target)) {
            $this->ensureDirectory($target);
            $changed = true;
        }
        $keep = [];
        foreach ($this->directoryEntries($source) as $entry) {
            $keep[$entry] = true;
            $sourcePath = $source . '/' . $entry;
            $targetPath = $target . '/' . $entry;
            if (is_dir($sourcePath)) {
                $this->syncDirectorySilently($sourcePath, $targetPath, $changed);
                continue;
            }
            if (!is_file($targetPath) || !$this->fileEquals($targetPath, $sourcePath)) {
                if (!$this->dryRun) {
                    copy($sourcePath, $targetPath);
                }
                $changed = true;
            }
        }
        $changed = $this->removeExtraEntries($target, $keep) || $changed;
    }

    /** Delete target entries not present in $keep; returns whether anything was removed. */
    private function removeExtraEntries(string $target, array $keep): bool
    {
        $removed = false;
        foreach ($this->directoryEntries($target) as $entry) {
            if (isset($keep[$entry])) {
                continue;
            }
            if (!$this->dryRun) {
                $this->deleteRecursively($target . '/' . $entry);
            }
            $removed = true;
        }
        return $removed;
    }

    /** Remove managed `hilos-*` children of $targetRoot whose source no longer exists. */
    private function pruneManagedChildren(string $targetRoot, array $expected, string $displayRoot): void
    {
        foreach ($this->directoryEntries($targetRoot) as $entry) {
            if (!str_starts_with($entry, self::MANAGED_CHILD_PREFIX) || isset($expected[$entry])) {
                continue;
            }
            if (!$this->dryRun) {
                $this->deleteRecursively($targetRoot . '/' . $entry);
            }
            $this->report(ArtifactStatus::Pruned, $displayRoot . '/' . $entry, 'source removed');
        }
    }

    /** @return list<string> absolute paths of `skills/hilos-*` directories, sorted */
    private function globSkillDirectories(string $relativeGlob): array
    {
        $matches = glob($this->absolute($relativeGlob), GLOB_ONLYDIR);
        if ($matches === false) {
            return [];
        }
        sort($matches);
        return $matches;
    }

    /** @return list<string> entry names in $dir excluding `.` and `..`, sorted */
    private function directoryEntries(string $dir): array
    {
        if (!is_dir($dir)) {
            return [];
        }
        $entries = array_values(array_diff(scandir($dir) ?: [], ['.', '..']));
        sort($entries);
        return $entries;
    }

    private function deleteRecursively(string $path): void
    {
        if (is_link($path) || is_file($path)) {
            unlink($path);
            return;
        }
        foreach ($this->directoryEntries($path) as $entry) {
            $this->deleteRecursively($path . '/' . $entry);
        }
        rmdir($path);
    }

    private function ensureDirectory(string $path): void
    {
        if (!$this->dryRun && !is_dir($path)) {
            mkdir($path, 0755, true);
        }
    }

    private function fileEquals(string $a, string $b): bool
    {
        return is_file($a) && is_file($b) && sha1_file($a) === sha1_file($b);
    }

    /** Compute a relative path from directory $fromDir to absolute $to (both absolute). */
    private function relativePath(string $fromDir, string $to): string
    {
        $from = explode('/', trim($fromDir, '/'));
        $dest = explode('/', trim($to, '/'));
        while ($from !== [] && $dest !== [] && $from[0] === $dest[0]) {
            array_shift($from);
            array_shift($dest);
        }
        return str_repeat('../', count($from)) . implode('/', $dest);
    }

    private function absolute(string $relative): string
    {
        return $this->repoRoot . '/' . $relative;
    }

    private function filesystemIsCaseInsensitive(): bool
    {
        $probe = $this->repoRoot . '/.hilos-ai-case-probe';
        file_put_contents($probe, '');
        $insensitive = file_exists($this->repoRoot . '/.HILOS-AI-CASE-PROBE');
        unlink($probe);
        return $insensitive;
    }

    private function filesystemSupportsSymlinks(): bool
    {
        $linkPath = $this->repoRoot . '/.hilos-ai-symlink-probe';
        $created = @symlink('agents.md', $linkPath);
        $supported = $created && is_link($linkPath);
        if (is_link($linkPath)) {
            unlink($linkPath);
        }
        return $supported;
    }

    private function report(ArtifactStatus $status, string $path, string $detail = ''): void
    {
        if ($status === ArtifactStatus::Blocked) {
            $this->blocks++;
        } elseif ($status->isChange()) {
            $this->changes++;
        }
        $suffix = $detail === '' ? '' : "  ({$detail})";
        echo '  [' . str_pad($status->value, 8) . "] {$path}{$suffix}\n";
    }

    private function summary(): int
    {
        if ($this->dryRun) {
            if ($this->changes === 0 && $this->blocks === 0) {
                echo "Up to date — no changes needed.\n";
                return 0;
            }
            echo "Drift detected: {$this->changes} change(s) pending, {$this->blocks} blocked. Run `composer ai:install`.\n";
            return 1;
        }

        echo "Done: {$this->changes} change(s) applied";
        echo $this->blocks > 0 ? ", {$this->blocks} blocked (resolve manually).\n" : ".\n";
        return $this->blocks > 0 ? 1 : 0;
    }
}

$options = array_slice($argv, 1);
if (in_array('--help', $options, true) || in_array('-h', $options, true)) {
    echo "Usage: php scripts/install-ai-tooling.php [--check] [--copy-only]\n";
    echo "  --check       report drift without changing anything (exit 1 on drift)\n";
    echo "  --copy-only   never create symlinks; copy/generate everywhere (Windows/CI)\n";
    exit(0);
}

$unknown = array_diff($options, ['--check', '--copy-only']);
if ($unknown !== []) {
    fwrite(STDERR, 'Unknown option(s): ' . implode(' ', $unknown) . "\n");
    exit(2);
}

try {
    $installer = new AiToolingInstaller(
        repoRoot: dirname(__DIR__),
        copyOnly: in_array('--copy-only', $options, true),
        dryRun: in_array('--check', $options, true),
    );
    exit($installer->run());
} catch (Throwable $error) {
    fwrite(STDERR, 'install-ai-tooling failed: ' . $error->getMessage() . "\n");
    exit(1);
}
