<?php

declare(strict_types=1);

/**
 * Cross-tool AI tooling installer for Hilos.
 *
 * Materializes per-tool AI configuration from the single source of truth
 * (`agents.md` + `docs/agents/` + `skills/hilos-*`) into the locations each
 * assistant discovers. The same idempotent pass performs first-run install,
 * repair (heals missing or wrong artifacts), and update (propagates canonical
 * changes); orphaned managed artifacts are pruned.
 *
 * Per artifact the strategy is chosen by how the tool discovers it:
 *   - symlink where the tool reads by an explicit named path,
 *   - copy/generate where the tool walks a directory (those walks skip symlinks).
 *
 * Generated artifacts are git-ignored and machine-local; every contributor runs
 * the installer to get artifacts correct for their OS. Run via:
 *
 *   composer ai:install            install / repair / update
 *   composer ai:install:check      report drift without changing anything (CI)
 *   php scripts/install-ai-tooling.php --copy-only    no symlinks (Windows/CI)
 *
 * Canonical sources, the tracked adapters (`CLAUDE.md`, `.cursor/rules/*`), and
 * the artifact map are documented in docs/agents/ai-tools.md.
 */

/** How a single artifact is materialized into the working tree. */
enum InstallStrategy
{
    /** Copy each `skills/hilos-*` directory into a tool's real skills directory. */
    case CopySkillTrees;
    /** Symlink each `skills/hilos-*` directory into a real parent (copy fallback). */
    case LinkSkillTrees;
    /** Single file symlink to a canonical file (copy fallback). */
    case SymlinkFile;
    /** Write fully-owned generated content. */
    case GenerateFile;
}

/** Outcome of materializing one path; drives the summary and exit code. */
enum ArtifactStatus: string
{
    case Created = 'created';
    case Updated = 'updated';
    case Repaired = 'repaired';
    case Ok = 'ok';
    case Pruned = 'pruned';
    case Skipped = 'skipped';
    case Blocked = 'blocked';

    public function isChange(): bool
    {
        return match ($this) {
            self::Created, self::Updated, self::Repaired, self::Pruned => true,
            self::Ok, self::Skipped, self::Blocked => false,
        };
    }
}

/** What a single planned write does to its path once the plan is applied. */
enum WriteKind
{
    /** Create the path as a regular file, or overwrite the one already there. */
    case File;
    /** Create the path as a directory, parents included. */
    case Directory;
    /** Create a symlink at the path. */
    case Symlink;
    /** Delete a file, a link, or a whole tree at the path. */
    case Removal;
}

/**
 * One write an artifact needs, described before anything touches the disk.
 *
 * The walk of a source tree builds a plain list of these, the list is judged for
 * feasibility as a whole, and only then applied — which is what makes a skill
 * all-or-nothing and lets one report name every path that cannot be written.
 */
final class PlannedWrite
{
    public function __construct(
        public readonly WriteKind $kind,
        public readonly string $path,
        public readonly ?string $source = null,
        public readonly ?string $body = null,
        public readonly ?string $linkTarget = null,
    ) {
    }
}

/**
 * Declarative description of one artifact the installer manages.
 *
 * This script stays compatible with the host PHP (8.1+) on purpose: it is a
 * dev-machine setup tool that must run without the framework's 8.4 docker
 * toolchain, so it avoids 8.2+-only syntax while remaining valid on 8.4.
 */
final class ArtifactSpec
{
    public function __construct(
        public readonly string $label,
        public readonly string $tools,
        public readonly InstallStrategy $strategy,
        public readonly string $target,
        public readonly ?string $source = null,
        public readonly ?string $sourceGlob = null,
        public readonly ?string $generatedBody = null,
        public readonly bool $caseSensitiveOnly = false,
    ) {
    }
}

final class AiToolingInstaller
{
    private const GENERATED_MARKER = 'generated by hilos composer ai:install';
    private const MANAGED_CHILD_PREFIX = 'hilos-';

    private int $changes = 0;
    private int $blocks = 0;

    public function __construct(
        private readonly string $repoRoot,
        private readonly bool $copyOnly,
        private readonly bool $dryRun,
    ) {
    }

    /** @return list<ArtifactSpec> */
    public static function artifacts(): array
    {
        $geminiBody = "<!-- " . self::GENERATED_MARKER . " — do not edit; canonical source: agents.md + docs/agents/ -->\n"
            . "# Hilos Framework\n\n"
            . "@./agents.md\n";

        $aiderBody = "# " . self::GENERATED_MARKER . " — do not edit; canonical source: agents.md + docs/agents/\n"
            . "read:\n"
            . "  - agents.md\n";

        return [
            new ArtifactSpec(
                label: 'Claude Code skills',
                tools: 'Claude Code',
                strategy: InstallStrategy::CopySkillTrees,
                target: '.claude/skills',
                sourceGlob: 'skills/' . self::MANAGED_CHILD_PREFIX . '*',
            ),
            new ArtifactSpec(
                label: 'Shared skill tree',
                tools: 'Codex, Cursor, Windsurf',
                strategy: InstallStrategy::LinkSkillTrees,
                target: '.agents/skills',
                sourceGlob: 'skills/' . self::MANAGED_CHILD_PREFIX . '*',
            ),
            new ArtifactSpec(
                label: 'AGENTS.md entry point',
                tools: 'Codex, Cursor, Windsurf, Aider',
                strategy: InstallStrategy::SymlinkFile,
                target: 'AGENTS.md',
                source: 'agents.md',
                caseSensitiveOnly: true,
            ),
            new ArtifactSpec(
                label: 'Gemini context',
                tools: 'Gemini CLI',
                strategy: InstallStrategy::GenerateFile,
                target: 'GEMINI.md',
                generatedBody: $geminiBody,
            ),
            new ArtifactSpec(
                label: 'Aider config',
                tools: 'Aider',
                strategy: InstallStrategy::GenerateFile,
                target: '.aider.conf.yml',
                generatedBody: $aiderBody,
            ),
        ];
    }

    /** Run the full pass and return a process exit code. */
    public function run(): int
    {
        $caseInsensitive = $this->filesystemIsCaseInsensitive();
        $symlinkCapable = $this->copyOnly ? false : $this->filesystemSupportsSymlinks();

        echo "Hilos AI tooling installer\n";
        echo "  repo:     {$this->repoRoot}\n";
        echo '  mode:     ' . ($this->dryRun ? 'check (no changes)' : 'install / repair / update') . "\n";
        echo '  symlinks: ' . ($symlinkCapable ? 'enabled' : 'disabled (copy / generate only)') . "\n";
        echo '  fs:       ' . ($caseInsensitive ? 'case-insensitive' : 'case-sensitive') . "\n";
        echo $this->rootWarningLine();
        echo "\n";

        foreach (self::artifacts() as $spec) {
            echo "{$spec->label}  ({$spec->tools})\n";

            if ($spec->caseSensitiveOnly && $caseInsensitive) {
                $this->report(ArtifactStatus::Skipped, $spec->target, 'case-insensitive filesystem already resolves it');
                echo "\n";
                continue;
            }

            match ($spec->strategy) {
                InstallStrategy::CopySkillTrees => $this->installSkillTrees($spec, false),
                InstallStrategy::LinkSkillTrees => $this->installSkillTrees($spec, $symlinkCapable),
                InstallStrategy::SymlinkFile => $this->installEntryPointFile($spec, $symlinkCapable),
                InstallStrategy::GenerateFile => $this->installGeneratedFile($spec),
            };
            echo "\n";
        }

        return $this->summary();
    }

    /** Copy or per-child symlink every `skills/hilos-*` directory into the target root. */
    private function installSkillTrees(ArtifactSpec $spec, bool $linkChildren): void
    {
        $sources = $this->globSkillDirectories($spec->sourceGlob);
        if ($sources === []) {
            $this->report(ArtifactStatus::Skipped, $spec->target, 'no source skill directories found');
            return;
        }

        $targetRoot = $this->absolute($spec->target);
        $rootBlockers = $this->performPlan(is_dir($targetRoot) ? [] : [new PlannedWrite(WriteKind::Directory, $targetRoot)]);
        if ($rootBlockers !== []) {
            $this->report(ArtifactStatus::Blocked, $spec->target, $this->blockDetail($rootBlockers, $spec->target));
            return;
        }

        $expected = [];
        foreach ($sources as $sourceDir) {
            $name = basename($sourceDir);
            $expected[$name] = true;
            $childTarget = $targetRoot . '/' . $name;

            if ($linkChildren) {
                $this->ensureSymlink($this->relativePath(dirname($childTarget), $sourceDir), $childTarget, $spec->target . '/' . $name);
            } else {
                $this->syncDirectory($sourceDir, $childTarget, $spec->target . '/' . $name);
            }
        }

        $this->pruneManagedChildren($targetRoot, $expected, $spec->target);
    }

    /** Maintain a single entry-point file as a symlink (or a real copy in copy mode). */
    private function installEntryPointFile(ArtifactSpec $spec, bool $symlinkCapable): void
    {
        $source = $this->absolute((string) $spec->source);
        if (!is_file($source)) {
            $this->report(ArtifactStatus::Skipped, $spec->target, "canonical source missing: {$spec->source}");
            return;
        }

        $target = $this->absolute($spec->target);

        if ($symlinkCapable) {
            $this->ensureSymlink($this->relativePath(dirname($target), $source), $target, $spec->target);
            return;
        }

        // Copy fallback: only own the file when it is absent or already equals the source.
        if (is_link($target) || (file_exists($target) && !$this->fileEquals($target, $source))) {
            $this->report(ArtifactStatus::Blocked, $spec->target, 'unexpected existing file; not overwriting');
            return;
        }
        if (is_file($target) && $this->fileEquals($target, $source)) {
            $this->report(ArtifactStatus::Ok, $spec->target);
            return;
        }
        $blockers = $this->performPlan([new PlannedWrite(WriteKind::File, $target, source: $source)]);
        if ($blockers !== []) {
            $this->report(ArtifactStatus::Blocked, $spec->target, $this->blockDetail($blockers, $spec->target));
            return;
        }
        $this->report(ArtifactStatus::Created, $spec->target, 'copied (no symlink support)');
    }

    /** Write a fully-owned generated file, refusing to clobber a foreign file at the path. */
    private function installGeneratedFile(ArtifactSpec $spec): void
    {
        $target = $this->absolute($spec->target);
        $body = (string) $spec->generatedBody;

        if (file_exists($target) && !is_link($target) && !str_contains((string) file_get_contents($target), self::GENERATED_MARKER)) {
            $this->report(ArtifactStatus::Blocked, $spec->target, 'existing non-generated file; not overwriting');
            return;
        }
        if (is_file($target) && !is_link($target) && file_get_contents($target) === $body) {
            $this->report(ArtifactStatus::Ok, $spec->target);
            return;
        }

        $existed = file_exists($target) || is_link($target);
        $plan = is_link($target) ? [new PlannedWrite(WriteKind::Removal, $target)] : [];
        $plan[] = new PlannedWrite(WriteKind::File, $target, body: $body);

        $blockers = $this->performPlan($plan);
        if ($blockers !== []) {
            $this->report(ArtifactStatus::Blocked, $spec->target, $this->blockDetail($blockers, $spec->target));
            return;
        }
        $this->report($existed ? ArtifactStatus::Updated : ArtifactStatus::Created, $spec->target);
    }

    /** Ensure $linkPath is a symlink pointing at $relativeTarget; repair if wrong, refuse foreign files. */
    private function ensureSymlink(string $relativeTarget, string $linkPath, string $displayPath): void
    {
        if (is_link($linkPath)) {
            if (readlink($linkPath) === $relativeTarget) {
                $this->report(ArtifactStatus::Ok, $displayPath);
                return;
            }
            $blockers = $this->performPlan([
                new PlannedWrite(WriteKind::Removal, $linkPath),
                new PlannedWrite(WriteKind::Symlink, $linkPath, linkTarget: $relativeTarget),
            ]);
            if ($blockers !== []) {
                $this->report(ArtifactStatus::Blocked, $displayPath, $this->blockDetail($blockers, $displayPath));
                return;
            }
            $this->report(ArtifactStatus::Repaired, $displayPath, "→ {$relativeTarget}");
            return;
        }

        if (file_exists($linkPath)) {
            $this->report(ArtifactStatus::Blocked, $displayPath, 'existing non-symlink file/dir; not replacing');
            return;
        }

        $blockers = $this->performPlan([new PlannedWrite(WriteKind::Symlink, $linkPath, linkTarget: $relativeTarget)]);
        if ($blockers !== []) {
            $this->report(ArtifactStatus::Blocked, $displayPath, $this->blockDetail($blockers, $displayPath));
            return;
        }
        $this->report(ArtifactStatus::Created, $displayPath, "→ {$relativeTarget}");
    }

    /** Mirror $source directory into $target, copying changed files and removing extras. */
    private function syncDirectory(string $source, string $target, string $displayPath): void
    {
        $existedAsTree = is_dir($target) && !is_link($target);
        if (is_link($target)) {
            $this->report(ArtifactStatus::Blocked, $displayPath, 'existing symlink where a copy is required; not replacing');
            return;
        }
        $plan = $this->planDirectorySync($source, $target);
        $blockers = $this->performPlan($plan);
        if ($blockers !== []) {
            $this->report(ArtifactStatus::Blocked, $displayPath, $this->blockDetail($blockers, $displayPath));
            return;
        }

        if (!$existedAsTree) {
            $this->report(ArtifactStatus::Created, $displayPath);
        } elseif ($plan !== []) {
            $this->report(ArtifactStatus::Updated, $displayPath);
        } else {
            $this->report(ArtifactStatus::Ok, $displayPath);
        }
    }

    /**
     * Walks $source and $target and writes down what mirroring one into the other
     * would take, without touching either. Nothing here is a side effect on
     * purpose: the caller judges the whole list first, so a tree that cannot be
     * mirrored is left as it was rather than half rewritten.
     *
     * @param string $source Absolute path of the source directory
     * @param string $target Absolute path of the directory it is mirrored into
     * @return list<PlannedWrite> Directories to create, files to copy, extras to delete
     */
    private function planDirectorySync(string $source, string $target): array
    {
        $plan = is_dir($target) ? [] : [new PlannedWrite(WriteKind::Directory, $target)];

        $keep = [];
        foreach ($this->directoryEntries($source) as $entry) {
            $keep[$entry] = true;
            $sourcePath = $source . '/' . $entry;
            $targetPath = $target . '/' . $entry;
            if (is_dir($sourcePath)) {
                foreach ($this->planDirectorySync($sourcePath, $targetPath) as $nested) {
                    $plan[] = $nested;
                }
                continue;
            }
            if (!is_file($targetPath) || !$this->fileEquals($targetPath, $sourcePath)) {
                $plan[] = new PlannedWrite(WriteKind::File, $targetPath, source: $sourcePath);
            }
        }

        foreach ($this->directoryEntries($target) as $entry) {
            if (!isset($keep[$entry])) {
                $plan[] = new PlannedWrite(WriteKind::Removal, $target . '/' . $entry);
            }
        }

        return $plan;
    }

    /**
     * @param list<PlannedWrite> $plan Writes to judge, and outside check mode to perform
     * @return array<string, string> Reason keyed by absolute path; empty when the plan went through
     */
    private function performPlan(array $plan): array
    {
        $blockers = $this->blockersFor($plan);
        if ($blockers !== [] || $this->dryRun) {
            return $blockers;
        }
        return $this->applyPlan($plan);
    }

    /**
     * @param list<PlannedWrite> $plan Writes to judge against the filesystem as it is now
     * @return array<string, string> Reason keyed by absolute path, in plan order
     */
    private function blockersFor(array $plan): array
    {
        $blockers = [];
        foreach ($plan as $write) {
            $blocker = $this->writeBlocker($write);
            if ($blocker !== null) {
                $blockers[$write->path] = $blocker;
            }
        }
        return $blockers;
    }

    /**
     * Reads feasibility off the filesystem rather than off a PHP warning, so the
     * common failure — a target somebody else owns — is named before any write is
     * issued and no warning is emitted for it.
     *
     * @param PlannedWrite $write Write whose feasibility is asked
     * @return string|null Reason the write cannot be made, or null when it can
     */
    private function writeBlocker(PlannedWrite $write): ?string
    {
        if ($write->kind === WriteKind::Removal) {
            return $this->removalBlocker($write->path);
        }

        if ($write->kind === WriteKind::File) {
            if (is_dir($write->path) && !is_link($write->path)) {
                return 'target is a directory where a file is required';
            }
            if (file_exists($write->path) || is_link($write->path)) {
                return is_writable($write->path) ? null : $this->permissionReason($write->path);
            }
        }

        if ($write->kind === WriteKind::Directory) {
            if (is_dir($write->path)) {
                return null;
            }
            if (file_exists($write->path) || is_link($write->path)) {
                return $this->display($write->path) . ' is a file where a directory is required';
            }
        }

        // Creating anything, and replacing a link, is granted by the nearest directory that already exists.
        $ancestor = dirname($write->path);
        while (!file_exists($ancestor) && !is_link($ancestor) && dirname($ancestor) !== $ancestor) {
            $ancestor = dirname($ancestor);
        }
        if (!is_dir($ancestor)) {
            return $this->display($ancestor) . ' is a file where a directory is required';
        }
        return is_writable($ancestor) ? null : $this->permissionReason($ancestor);
    }

    /**
     * POSIX grants removal through the containing directory rather than through the
     * entry, and a tree comes out one entry at a time — so every directory on the
     * way has to be writable, not just the top one.
     *
     * @param string $path Absolute path about to be deleted
     * @return string|null Reason the deletion cannot happen, or null when it can
     */
    private function removalBlocker(string $path): ?string
    {
        if (!is_writable(dirname($path))) {
            return $this->permissionReason(dirname($path));
        }
        if (is_link($path) || !is_dir($path)) {
            return null;
        }
        if (!is_writable($path)) {
            return $this->permissionReason($path);
        }
        foreach ($this->directoryEntries($path) as $entry) {
            $blocker = $this->removalBlocker($path . '/' . $entry);
            if ($blocker !== null) {
                return $blocker;
            }
        }
        return null;
    }

    /**
     * The second layer over feasibility: a write can still fail on a race, a full
     * disk or an immutable flag, and such a failure becomes a block rather than a
     * change, exactly like one the first layer predicted.
     *
     * @param list<PlannedWrite> $plan Writes already judged performable
     * @return array<string, string> Reason keyed by absolute path of every write that failed anyway
     */
    private function applyPlan(array $plan): array
    {
        $failures = [];
        foreach ($plan as $write) {
            error_clear_last();
            $done = match ($write->kind) {
                WriteKind::File => $write->body === null
                    ? copy((string) $write->source, $write->path)
                    : file_put_contents($write->path, $write->body) !== false,
                WriteKind::Directory => $this->ensureDirectory($write->path),
                WriteKind::Symlink => symlink((string) $write->linkTarget, $write->path),
                WriteKind::Removal => $this->deleteRecursively($write->path),
            };
            if (!$done) {
                $failures[$write->path] = 'write failed: ' . (error_get_last()['message'] ?? 'unknown');
            }
        }
        return $failures;
    }

    /**
     * One line per artifact, because the operator repairs ownership by directory:
     * it names how much is unwritable, why, and the command that fixes it.
     *
     * @param array<string, string> $blockers Reason keyed by absolute path, non-empty
     * @param string $displayPath Artifact path as reported, relative to the repository root
     * @return string Detail printed in parentheses after the blocked artifact
     */
    private function blockDetail(array $blockers, string $displayPath): string
    {
        $reason = (string) reset($blockers);
        $blockedPath = (string) array_key_first($blockers);
        $single = count($blockers) === 1;
        $head = $single
            ? 'cannot overwrite ' . $this->display($blockedPath) . ': ' . $reason
            : 'cannot write ' . count($blockers) . ' file(s): ' . $reason;

        $command = $this->ownershipCommand($single ? $blockedPath : $this->absolute($displayPath));
        return $head . ' — ' . ($command === '' ? 'fix ownership or rerun as the owner' : $command);
    }

    /**
     * @param string $path Absolute path whose ownership the operator has to take
     * @return string Ready-to-paste chown, or an empty string where ext-posix cannot name the user
     */
    private function ownershipCommand(string $path): string
    {
        if (!function_exists('posix_geteuid') || !function_exists('posix_getpwuid') || !function_exists('posix_getgrgid')) {
            return '';
        }
        $user = posix_getpwuid(posix_geteuid());
        $group = posix_getgrgid(posix_getegid());
        if ($user === false || $group === false) {
            return '';
        }
        $command = is_dir($path) ? 'sudo chown -R ' : 'sudo chown ';
        return $command . $user['name'] . ':' . $group['name'] . ' ' . $this->display($path);
    }

    /**
     * @param string $path Absolute path that refused the write
     * @return string Reason naming the owner, or the bare reason where ext-posix cannot name one
     */
    private function permissionReason(string $path): string
    {
        $owner = $this->ownerName($path);
        return $owner === null ? 'permission denied' : "permission denied (owner {$owner})";
    }

    /**
     * @param string $path Absolute path whose owner is asked
     * @return string|null Login name of the owner, or null without ext-posix
     */
    private function ownerName(string $path): ?string
    {
        if (!function_exists('posix_getpwuid')) {
            return null;
        }
        $uid = fileowner($path);
        if ($uid === false) {
            return null;
        }
        $entry = posix_getpwuid($uid);
        return $entry === false ? null : (string) $entry['name'];
    }

    /**
     * Warns the one run that manufactures the very defect this installer refuses:
     * root writing into somebody else's checkout. A checkout root owned by root —
     * CI, a container — is the normal case and says nothing.
     *
     * @return string Header line to print, or an empty string when there is nothing to warn about
     */
    private function rootWarningLine(): string
    {
        if (!function_exists('posix_geteuid') || posix_geteuid() !== 0) {
            return '';
        }
        $uid = fileowner($this->repoRoot);
        if ($uid === false || $uid === 0) {
            return '';
        }
        $owner = $this->ownerName($this->repoRoot) ?? (string) $uid;
        return "  warning:  running as root while {$owner} owns this checkout — artifacts created now will be owned"
            . " by root, and a later run as {$owner} will be refused\n";
    }

    /**
     * @param string $absolute Absolute path inside the repository
     * @return string The same path relative to the repository root, for report text
     */
    private function display(string $absolute): string
    {
        $prefix = $this->repoRoot . '/';
        return str_starts_with($absolute, $prefix) ? substr($absolute, strlen($prefix)) : $absolute;
    }

    /** Remove managed `hilos-*` children of $targetRoot whose source no longer exists. */
    private function pruneManagedChildren(string $targetRoot, array $expected, string $displayRoot): void
    {
        foreach ($this->directoryEntries($targetRoot) as $entry) {
            if (!str_starts_with($entry, self::MANAGED_CHILD_PREFIX) || isset($expected[$entry])) {
                continue;
            }
            $displayPath = $displayRoot . '/' . $entry;
            $blockers = $this->performPlan([new PlannedWrite(WriteKind::Removal, $targetRoot . '/' . $entry)]);
            if ($blockers !== []) {
                $this->report(ArtifactStatus::Blocked, $displayPath, $this->blockDetail($blockers, $displayPath));
                continue;
            }
            $this->report(ArtifactStatus::Pruned, $displayPath, 'source removed');
        }
    }

    /** @return list<string> absolute paths of `skills/hilos-*` directories, sorted */
    private function globSkillDirectories(?string $relativeGlob): array
    {
        if ($relativeGlob === null) {
            return [];
        }
        $matches = glob($this->absolute($relativeGlob), GLOB_ONLYDIR);
        if ($matches === false) {
            return [];
        }
        sort($matches);
        return $matches;
    }

    /** @return list<string> entry names in $dir excluding `.` and `..`, sorted */
    private function directoryEntries(string $dir): array
    {
        if (!is_dir($dir)) {
            return [];
        }
        $entries = array_values(array_diff(scandir($dir) ?: [], ['.', '..']));
        sort($entries);
        return $entries;
    }

    /**
     * Apply step of a {@see WriteKind::Removal} entry; stops at the first entry that
     * survives, so the caller reports a block instead of a removal that never was.
     *
     * @param string $path Absolute path to delete
     * @return bool True when nothing is left at the path
     */
    private function deleteRecursively(string $path): bool
    {
        if (is_link($path) || is_file($path)) {
            return unlink($path);
        }
        foreach ($this->directoryEntries($path) as $entry) {
            if (!$this->deleteRecursively($path . '/' . $entry)) {
                return false;
            }
        }
        return rmdir($path);
    }

    /**
     * Apply step of a {@see WriteKind::Directory} entry.
     *
     * @param string $path Absolute path of the directory
     * @return bool True when the directory is there afterwards
     */
    private function ensureDirectory(string $path): bool
    {
        return is_dir($path) || mkdir($path, 0755, true);
    }

    private function fileEquals(string $a, string $b): bool
    {
        return is_file($a) && is_file($b) && sha1_file($a) === sha1_file($b);
    }

    /** Compute a relative path from directory $fromDir to absolute $to (both absolute). */
    private function relativePath(string $fromDir, string $to): string
    {
        $from = explode('/', trim($fromDir, '/'));
        $dest = explode('/', trim($to, '/'));
        while ($from !== [] && $dest !== [] && $from[0] === $dest[0]) {
            array_shift($from);
            array_shift($dest);
        }
        return str_repeat('../', count($from)) . implode('/', $dest);
    }

    private function absolute(string $relative): string
    {
        return $this->repoRoot . '/' . $relative;
    }

    private function filesystemIsCaseInsensitive(): bool
    {
        $probe = $this->repoRoot . '/.hilos-ai-case-probe';
        file_put_contents($probe, '');
        $insensitive = file_exists($this->repoRoot . '/.HILOS-AI-CASE-PROBE');
        unlink($probe);
        return $insensitive;
    }

    private function filesystemSupportsSymlinks(): bool
    {
        $linkPath = $this->repoRoot . '/.hilos-ai-symlink-probe';
        // warning-suppressed: a filesystem refusing the link is the answer this probe asks for, and the next line reads it back
        $created = @symlink('agents.md', $linkPath);
        $supported = $created && is_link($linkPath);
        if (is_link($linkPath)) {
            unlink($linkPath);
        }
        return $supported;
    }

    private function report(ArtifactStatus $status, string $path, string $detail = ''): void
    {
        if ($status === ArtifactStatus::Blocked) {
            $this->blocks++;
        } elseif ($status->isChange()) {
            $this->changes++;
        }
        $suffix = $detail === '' ? '' : "  ({$detail})";
        echo '  [' . str_pad($status->value, 8) . "] {$path}{$suffix}\n";
    }

    private function summary(): int
    {
        if ($this->dryRun) {
            if ($this->changes === 0 && $this->blocks === 0) {
                echo "Up to date — no changes needed.\n";
                return 0;
            }
            if ($this->blocks === 0) {
                echo "Drift detected: {$this->changes} change(s) pending. Run `composer ai:install`.\n";
            } elseif ($this->changes === 0) {
                echo "Drift detected: {$this->blocks} blocked — `composer ai:install` cannot fix these; resolve them first.\n";
            } else {
                echo "Drift detected: {$this->changes} change(s) pending, {$this->blocks} blocked."
                    . " Run `composer ai:install` for the pending ones;"
                    . " the blocked ones it cannot fix — resolve them first.\n";
            }
            return 1;
        }

        echo "Done: {$this->changes} change(s) applied";
        echo $this->blocks > 0 ? ", {$this->blocks} blocked (resolve manually).\n" : ".\n";
        return $this->blocks > 0 ? 1 : 0;
    }
}

$options = array_slice($argv, 1);
if (in_array('--help', $options, true) || in_array('-h', $options, true)) {
    echo "Usage: php scripts/install-ai-tooling.php [--check] [--copy-only]\n";
    echo "  --check       report drift without changing anything (exit 1 on drift)\n";
    echo "  --copy-only   never create symlinks; copy/generate everywhere (Windows/CI)\n";
    exit(0);
}

$unknown = array_diff($options, ['--check', '--copy-only']);
if ($unknown !== []) {
    fwrite(STDERR, 'Unknown option(s): ' . implode(' ', $unknown) . "\n");
    exit(2);
}

try {
    $installer = new AiToolingInstaller(
        repoRoot: dirname(__DIR__),
        copyOnly: in_array('--copy-only', $options, true),
        dryRun: in_array('--check', $options, true),
    );
    exit($installer->run());
} catch (Throwable $error) {
    fwrite(STDERR, 'install-ai-tooling failed: ' . $error->getMessage() . "\n");
    exit(1);
}
