// The framework's own page catalog: the keys and cold-load URL templates of the
// Hilos admin section (dashboard, i18n, daemon, logs, users, MCP/skills, SIL,
// communications, security, billing, change log). These pages are framework
// functionality, so the framework owns their identity and URL layout — a
// project mounts them by merging HILOS_PAGE_ROUTES into its own route map
// rather than restating them. Keys mirror PHP `HilosPageConstants` and the
// templates mirror the framework rows of the page catalog; both must stay
// byte-identical to their backend counterparts (the page key is the
// subscription wire identity, the path is the canonical admin URL).

/** Hilos admin page keys, mirroring PHP `HilosPageConstants`. */
export const HilosPages = {
  DASHBOARD: 'hilos',
  SETTINGS: 'hilos_settings',
  ANALYTICS: 'hilos_analytics',
  ROLES: 'hilos_roles',
  OPERATIONS: 'hilos_operations',
  BACKUP: 'hilos_backup',
  GUARDIAN: 'hilos_guardian',
  GUARDIAN_AGENT: 'hilos_guardian_agent',
  I18N: 'hilos_i18n',
  I18N_LANGUAGES: 'hilos_i18n_languages',
  I18N_COUNTRIES: 'hilos_i18n_countries',
  I18N_ENTITIES: 'hilos_i18n_entities',
  I18N_UI_PAGES: 'hilos_i18n_ui_pages',
  I18N_GROUPS: 'hilos_i18n_groups',
  I18N_ACTIONS: 'hilos_i18n_actions',
  I18N_EMAILS: 'hilos_i18n_emails',
  I18N_LANGUAGE: 'hilos_i18n_language',
  I18N_COUNTRY: 'hilos_i18n_country',
  I18N_UI_PAGE: 'hilos_i18n_ui_page',
  I18N_GROUP: 'hilos_i18n_group',
  I18N_ACTION: 'hilos_i18n_action',
  I18N_TRANSLATE_ENTITY: 'hilos_i18n_translate_entity',
  I18N_TRANSLATE_UI_PAGE: 'hilos_i18n_translate_ui_page',
  I18N_TRANSLATE_UI_PAGE_ITEM: 'hilos_i18n_translate_ui_page_item',
  I18N_TRANSLATE_GROUP: 'hilos_i18n_translate_group',
  I18N_TRANSLATE_GROUP_ITEM: 'hilos_i18n_translate_group_item',
  I18N_TRANSLATE_ACTION_ERROR: 'hilos_i18n_translate_action_error',
  I18N_TRANSLATE_EMAIL: 'hilos_i18n_translate_email',
  CHANGE_LOG: 'hilos_change_log',
  CHANGE_LOG_TABLES: 'hilos_change_log_tables',
  CHANGE_LOG_TABLE: 'hilos_change_log_table',
  DAEMON: 'hilos_daemon',
  DAEMON_WORKERS: 'hilos_daemon_workers',
  DAEMON_AGENTS: 'hilos_daemon_agents',
  DAEMON_CRON: 'hilos_daemon_cron',
  DAEMON_WEBSOCKETS: 'hilos_daemon_websockets',
  DAEMON_HTTP_SERVER: 'hilos_daemon_http_server',
  LOGS: 'hilos_logs',
  LOGS_KEYS: 'hilos_logs_keys',
  LOGS_WORKERS: 'hilos_logs_workers',
  LOGS_ROTATIONS: 'hilos_logs_rotations',
  LOGS_VIEW: 'hilos_logs_view',
  USERS: 'hilos_users',
  USER: 'hilos_user',
  MCP_SKILLS: 'hilos_mcp_skills',
  MCP_SKILLS_MCP: 'hilos_mcp_skills_mcp',
  MCP_SKILLS_MCP_LOGS: 'hilos_mcp_skills_mcp_logs',
  MCP_SKILLS_MCP_LOGS_VIEW: 'hilos_mcp_skills_mcp_logs_view',
  SIL: 'hilos_sil',
  SIL_REQUESTS: 'hilos_sil_requests',
  SIL_USER_HISTORY: 'hilos_sil_user_history',
  COMMUNICATIONS: 'hilos_communications',
  COMMUNICATIONS_CHANNEL: 'hilos_communications_channel',
  COMMUNICATIONS_DELIVERIES: 'hilos_communications_deliveries',
  SECURITY: 'hilos_security',
  SECURITY_2FA: 'hilos_security_2fa',
  SECURITY_OAUTH: 'hilos_security_oauth',
  SECURITY_OAUTH_PROVIDER: 'hilos_security_oauth_provider',
  BILLING: 'hilos_billing',
  BILLING_PROVIDER: 'hilos_billing_provider',
  BILLING_PAYMENTS: 'hilos_billing_payments',
  BILLING_REFUNDS: 'hilos_billing_refunds',
} as const

/**
 * Hilos admin page key → cold-load URL template, mirroring the framework rows
 * of the page catalog. `{name}` segments are route params captured at match
 * time. A project spreads this into its own route map to mount the admin.
 */
export const HILOS_PAGE_ROUTES: Record<string, string> = {
  [HilosPages.DASHBOARD]: '/hilos',
  [HilosPages.SETTINGS]: '/hilos/settings',
  [HilosPages.ANALYTICS]: '/hilos/analytics',
  [HilosPages.ROLES]: '/hilos/roles',
  [HilosPages.OPERATIONS]: '/hilos/operations',
  [HilosPages.BACKUP]: '/hilos/backup',
  [HilosPages.GUARDIAN]: '/hilos/guardian',
  [HilosPages.GUARDIAN_AGENT]: '/hilos/guardian/{agentId}',
  [HilosPages.I18N]: '/hilos/i18n',
  [HilosPages.I18N_LANGUAGES]: '/hilos/i18n/languages',
  [HilosPages.I18N_COUNTRIES]: '/hilos/i18n/countries',
  [HilosPages.I18N_ENTITIES]: '/hilos/i18n/entities',
  [HilosPages.I18N_UI_PAGES]: '/hilos/i18n/ui-pages',
  [HilosPages.I18N_GROUPS]: '/hilos/i18n/groups',
  [HilosPages.I18N_ACTIONS]: '/hilos/i18n/actions',
  [HilosPages.I18N_EMAILS]: '/hilos/i18n/emails',
  [HilosPages.I18N_LANGUAGE]: '/hilos/i18n/languages/{languageId}',
  [HilosPages.I18N_COUNTRY]: '/hilos/i18n/countries/{countryId}',
  [HilosPages.I18N_UI_PAGE]: '/hilos/i18n/ui-pages/{uiPageId}',
  [HilosPages.I18N_GROUP]: '/hilos/i18n/groups/{groupId}',
  [HilosPages.I18N_ACTION]: '/hilos/i18n/actions/{actionId}',
  [HilosPages.I18N_TRANSLATE_ENTITY]: '/hilos/i18n/translate/entity/{entityId}',
  [HilosPages.I18N_TRANSLATE_UI_PAGE]:
    '/hilos/i18n/translate/ui-page/{uiPageId}',
  [HilosPages.I18N_TRANSLATE_UI_PAGE_ITEM]:
    '/hilos/i18n/translate/ui-page/{uiPageId}/item/{itemId}',
  [HilosPages.I18N_TRANSLATE_GROUP]: '/hilos/i18n/translate/group/{groupId}',
  [HilosPages.I18N_TRANSLATE_GROUP_ITEM]:
    '/hilos/i18n/translate/group/{groupId}/item/{itemId}',
  [HilosPages.I18N_TRANSLATE_ACTION_ERROR]:
    '/hilos/i18n/translate/action/{actionId}/error/{errorId}',
  [HilosPages.I18N_TRANSLATE_EMAIL]: '/hilos/i18n/translate/email/{emailId}',
  [HilosPages.CHANGE_LOG]: '/hilos/change-log',
  [HilosPages.CHANGE_LOG_TABLES]: '/hilos/change-log/tables',
  [HilosPages.CHANGE_LOG_TABLE]: '/hilos/change-log/tables/{tableId}',
  [HilosPages.DAEMON]: '/hilos/daemon',
  [HilosPages.DAEMON_WORKERS]: '/hilos/daemon/workers',
  [HilosPages.DAEMON_AGENTS]: '/hilos/daemon/agents',
  [HilosPages.DAEMON_CRON]: '/hilos/daemon/cron',
  [HilosPages.DAEMON_WEBSOCKETS]: '/hilos/daemon/websockets',
  [HilosPages.DAEMON_HTTP_SERVER]: '/hilos/daemon/http/{serverId}',
  [HilosPages.LOGS]: '/hilos/logs',
  [HilosPages.LOGS_KEYS]: '/hilos/logs/keys',
  [HilosPages.LOGS_WORKERS]: '/hilos/logs/workers',
  [HilosPages.LOGS_ROTATIONS]: '/hilos/logs/rotations',
  [HilosPages.LOGS_VIEW]: '/hilos/logs/view',
  [HilosPages.USERS]: '/hilos/users',
  [HilosPages.USER]: '/hilos/users/{userId}',
  [HilosPages.MCP_SKILLS]: '/hilos/mcp-skills',
  [HilosPages.MCP_SKILLS_MCP]: '/hilos/mcp-skills/{mcpId}',
  [HilosPages.MCP_SKILLS_MCP_LOGS]: '/hilos/mcp-skills/{mcpId}/logs',
  [HilosPages.MCP_SKILLS_MCP_LOGS_VIEW]: '/hilos/mcp-skills/{mcpId}/logs/view',
  [HilosPages.SIL]: '/hilos/sil',
  [HilosPages.SIL_REQUESTS]: '/hilos/sil/requests',
  [HilosPages.SIL_USER_HISTORY]: '/hilos/sil/users/{userId}',
  [HilosPages.COMMUNICATIONS]: '/hilos/communications',
  [HilosPages.COMMUNICATIONS_CHANNEL]: '/hilos/communications/{channelId}',
  [HilosPages.COMMUNICATIONS_DELIVERIES]:
    '/hilos/communications/{channelId}/deliveries',
  [HilosPages.SECURITY]: '/hilos/security',
  [HilosPages.SECURITY_2FA]: '/hilos/security/2fa',
  [HilosPages.SECURITY_OAUTH]: '/hilos/security/oauth',
  [HilosPages.SECURITY_OAUTH_PROVIDER]: '/hilos/security/oauth/{providerId}',
  [HilosPages.BILLING]: '/hilos/billing',
  [HilosPages.BILLING_PROVIDER]: '/hilos/billing/{providerId}',
  [HilosPages.BILLING_PAYMENTS]: '/hilos/billing/{providerId}/payments',
  [HilosPages.BILLING_REFUNDS]: '/hilos/billing/{providerId}/refunds',
}
