/**
 * Route definitions for Vite SSG and Vue Router.
 * Hilos admin routes are provided by the framework, with explicit demo overrides.
 */
import type { RouteRecordRaw } from 'vue-router'
import { createHilosRoutes } from '@hilos/sdk/router/hilosRoutes'
import Layout from '@/components/Layout.vue'

const hilosRouteOverrides = {
  hilos: () => import('@/views/Hilos/HilosDashboard.vue'),
  hilos_backup: () => import('@/views/Hilos/Backup/HilosBackup.vue'),
  hilos_billing: () => import('@/views/Hilos/Billing/HilosBilling.vue'),
  hilos_billing_payments: () => import('@/views/Hilos/Billing/HilosBillingPayments.vue'),
  hilos_billing_provider: () => import('@/views/Hilos/Billing/HilosBillingProvider.vue'),
  hilos_billing_refunds: () => import('@/views/Hilos/Billing/HilosBillingRefunds.vue'),
  hilos_analytics: () => import('@/views/Hilos/HilosAnalytics.vue'),
  hilos_change_log: () => import('@/views/Hilos/ChangeLog/HilosChangeLogDashboard.vue'),
  hilos_change_log_table: () => import('@/views/Hilos/ChangeLog/HilosChangeLogTable.vue'),
  hilos_change_log_tables: () => import('@/views/Hilos/ChangeLog/HilosChangeLogTables.vue'),
  hilos_communications: () => import('@/views/Hilos/HilosCommunications.vue'),
  hilos_communications_channel: () => import('@/views/Hilos/Communications/HilosCommunicationsChannel.vue'),
  hilos_communications_deliveries: () => import('@/views/Hilos/Communications/HilosCommunicationsDeliveries.vue'),
  hilos_daemon: () => import('@/views/Hilos/Daemon/HilosDaemon.vue'),
  hilos_daemon_cron: () => import('@/views/Hilos/Daemon/HilosDaemonCron.vue'),
  hilos_daemon_http_server: () => import('@/views/Hilos/Daemon/HilosDaemonHttpServer.vue'),
  hilos_guardian: () => import('@/views/Hilos/HilosGuardian.vue'),
  hilos_i18n: () => import('@/views/Hilos/HilosI18n.vue'),
  hilos_i18n_actions: () => import('@/views/Hilos/I18n/Lists/HilosI18nActionsList.vue'),
  hilos_i18n_countries: () => import('@/views/Hilos/I18n/Lists/HilosI18nCountriesList.vue'),
  hilos_i18n_country: () => import('@/views/Hilos/I18n/Details/HilosI18nCountryDetail.vue'),
  hilos_i18n_emails: () => import('@/views/Hilos/I18n/Lists/HilosI18nEmailsList.vue'),
  hilos_i18n_entities: () => import('@/views/Hilos/I18n/Lists/HilosI18nEntitiesList.vue'),
  hilos_i18n_group: () => import('@/views/Hilos/I18n/Details/HilosI18nGroupDetail.vue'),
  hilos_i18n_groups: () => import('@/views/Hilos/I18n/Lists/HilosI18nGroupsList.vue'),
  hilos_i18n_action: () => import('@/views/Hilos/I18n/Details/HilosI18nActionDetail.vue'),
  hilos_i18n_language: () => import('@/views/Hilos/I18n/Details/HilosI18nLanguageDetail.vue'),
  hilos_i18n_translate_action_error: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateActionError.vue'),
  hilos_i18n_translate_email: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateEmail.vue'),
  hilos_i18n_translate_entity: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateEntity.vue'),
  hilos_i18n_translate_group: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateGroup.vue'),
  hilos_i18n_translate_group_item: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateGroupItem.vue'),
  hilos_i18n_translate_ui_page: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateUiPage.vue'),
  hilos_i18n_translate_ui_page_item: () => import('@/views/Hilos/I18n/Translate/HilosI18nTranslateUiPageItem.vue'),
  hilos_i18n_ui_page: () => import('@/views/Hilos/I18n/Details/HilosI18nUiPageDetail.vue'),
  hilos_i18n_languages: () => import('@/views/Hilos/I18n/Lists/HilosI18nLanguagesList.vue'),
  hilos_i18n_ui_pages: () => import('@/views/Hilos/I18n/Lists/HilosI18nUiPagesList.vue'),
  hilos_daemon_agents: () => import('@/views/Hilos/Daemon/HilosDaemonAgents.vue'),
  hilos_daemon_websockets: () => import('@/views/Hilos/Daemon/HilosDaemonWebsockets.vue'),
  hilos_daemon_workers: () => import('@/views/Hilos/Daemon/HilosDaemonWorkers.vue'),
  hilos_guardian_agent: () => import('@/views/Hilos/HilosGuardianAgent.vue'),
  hilos_logs: () => import('@/views/Hilos/LogViewer/HilosLogs.vue'),
  hilos_logs_keys: () => import('@/views/Hilos/LogViewer/HilosLogsKeys.vue'),
  hilos_logs_rotations: () => import('@/views/Hilos/LogViewer/HilosLogsRotations.vue'),
  hilos_logs_view: () => import('@/views/Hilos/LogViewer/HilosLogsView.vue'),
  hilos_logs_workers: () => import('@/views/Hilos/LogViewer/HilosLogsWorkers.vue'),
  hilos_mcp_skills: () => import('@/views/Hilos/McpSkills/HilosMcpSkillsDashboard.vue'),
  hilos_mcp_skills_mcp: () => import('@/views/Hilos/McpSkills/HilosMcpSkillsMcp.vue'),
  hilos_mcp_skills_mcp_logs: () => import('@/views/Hilos/McpSkills/HilosMcpSkillsMcpLogs.vue'),
  hilos_mcp_skills_mcp_logs_view: () => import('@/views/Hilos/McpSkills/HilosMcpSkillsMcpLogsView.vue'),
  hilos_operations: () => import('@/views/Hilos/HilosOperations.vue'),
  hilos_roles: () => import('@/views/Hilos/HilosRoles.vue'),
  hilos_security: () => import('@/views/Hilos/HilosSecurity.vue'),
  hilos_security_2fa: () => import('@/views/Hilos/Security/HilosSecurityTwoFactor.vue'),
  hilos_security_oauth: () => import('@/views/Hilos/Security/HilosSecurityOAuth.vue'),
  hilos_security_oauth_provider: () => import('@/views/Hilos/Security/HilosSecurityOAuthProvider.vue'),
  hilos_settings: () => import('@/views/Hilos/HilosSettings.vue'),
  hilos_sil: () => import('@/views/Hilos/Sil/HilosSilDashboard.vue'),
  hilos_sil_requests: () => import('@/views/Hilos/Sil/HilosSilRequests.vue'),
  hilos_sil_user_history: () => import('@/views/Hilos/Sil/HilosSilUserHistory.vue'),
  hilos_user: () => import('@/views/Hilos/HilosUserDetail.vue'),
  hilos_users: () => import('@/views/Hilos/HilosUsers.vue'),
}

export const demoRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: Layout,
    children: [
      {
        path: '',
        name: 'home',
        component: () => import('@/views/Home.vue'),
        meta: { page: 'main' },
      },
      {
        path: 'profile',
        name: 'profile',
        component: () => import('@/views/Profile.vue'),
        meta: { page: 'profile' },
      },
      {
        path: 'hilos/admin_users',
        name: 'admin_users',
        component: () => import('@/views/AdminUsers.vue'),
        meta: { page: 'admin_users' },
      },
      {
        path: 'hilos/admin_moderator',
        name: 'admin_moderator',
        component: () => import('@/views/AdminModerator.vue'),
        meta: { page: 'admin_moderator' },
      },
      {
        path: 'hilos/admin_bots',
        name: 'admin_bots',
        component: () => import('@/views/AdminBots.vue'),
        meta: { page: 'admin_bots' },
      },
      {
        path: 'user/:id',
        name: 'user',
        component: () => import('@/views/User.vue'),
        meta: { page: 'user' },
      },
      {
        path: 'bot/:id',
        name: 'bot',
        component: () => import('@/views/Bot.vue'),
        meta: { page: 'bot' },
      },
      {
        path: 'licence',
        name: 'licence',
        component: () => import('@/views/Licence.vue'),
      },
      {
        path: 'terms',
        name: 'terms',
        component: () => import('@/views/Terms.vue'),
      },
      {
        path: 'privacy',
        name: 'privacy',
        component: () => import('@/views/Privacy.vue'),
      },
      {
        path: 'agents',
        name: 'agents',
        component: () => import('@/views/Agents.vue'),
      },
      ...((createHilosRoutes(hilosRouteOverrides) as unknown) as RouteRecordRaw[]),
    ],
  },
  { path: '/400', name: 'error-400', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 400 } },
  { path: '/401', name: 'error-401', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 401 } },
  { path: '/402', name: 'error-402', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 402 } },
  { path: '/403', name: 'error-403', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 403 } },
  { path: '/404', name: 'error-404', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 404 } },
  { path: '/405', name: 'error-405', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 405 } },
  { path: '/408', name: 'error-408', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 408 } },
  { path: '/409', name: 'error-409', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 409 } },
  { path: '/410', name: 'error-410', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 410 } },
  { path: '/429', name: 'error-429', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 429 } },
  { path: '/500', name: 'error-500', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 500 } },
  { path: '/502', name: 'error-502', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 502 } },
  { path: '/503', name: 'error-503', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 503 } },
  { path: '/504', name: 'error-504', component: () => import('@/views/ErrorPage.vue'), meta: { errorCode: 504 } },
]
